### ISSUE TITLE
Mapeamento e código do banco de dados

### ISSUE THREAD

**Issue by WellingtonCrivellari** [FilipeSNascimento/Loja-Virtual#12]
Diagrama de entidades feito no Lucid.app

**Comment by WellingtonCrivellari** [comment]
### diagrama de entidades 




![Image](https://github.com/FilipeSNascimento/Loja-Virtual/assets/100310182/b8ca9113-a325-4d7a-9fb6-cd09c6fe828b)

**Comment by PedroR2401** [comment]
![Image](https://github.com/FilipeSNascimento/Loja-Virtual/assets/99568069/f4dfe851-0595-47b0-b5e4-2a1783fba067)
