### ISSUE TITLE
DDL Banco de dados (Credenciais)

### ISSUE THREAD

**Issue by WellingtonCrivellari** [FilipeSNascimento/Loja-Virtual#15]

**Comment by WellingtonCrivellari** [comment]
![Image](https://github.com/FilipeSNascimento/Loja-Virtual/assets/100310182/ad5e20c5-7c61-429e-a630-a6700b45c061)




```sql
create table credenciais(
    idCredenciais serial primary key,
    email varchar(50) not null,
    senha varchar(55) not null
);
```

**Comment by FilipeSNascimento** [comment]
```sql
create table tb_credenciais(
    idCredenciais serial primary key,
    email varchar(50) not null,
    senha varchar(55) not null
);
```
Realizei uma mudança no nome da tabela para melhor identificação

**Comment by PedroR2401** [comment]
Alterado os nomes e tipos dos atributos

![Image](https://github.com/FilipeSNascimento/Loja-Virtual/assets/99568069/1f0ae0ba-92b1-43bc-8ff5-7a14eefbbe31)
