### ISSUE TITLE
DDL Banco de dados (Categorias)

### ISSUE THREAD

**Issue by WellingtonCrivellari** [FilipeSNascimento/Loja-Virtual#16]

**Comment by WellingtonCrivellari** [comment]
![Image](https://github.com/FilipeSNascimento/Loja-Virtual/assets/100310182/1da5b6b4-fa29-4950-b3a3-215c14cf1629)





```sql
create table categorias(
    idCategoria serial primary key,
    nome varchar(15)
);
```

**Comment by FilipeSNascimento** [comment]
```sql
create table categorias(
    idCategoria serial primary key,
    nome varchar(15)
);
```
Realizei uma mudança no nome da tabela para melhor identificação

**Comment by PedroR2401** [comment]
![Image](https://github.com/FilipeSNascimento/Loja-Virtual/assets/99568069/e3cf573c-5d06-4141-bc18-37821e756aaa)
